[package]
name = "clipper"
version = "0.2.1"
authors = ["insomnimus <insomnimus19@gmail.com>"]
edition = "2018"


[dependencies]
atty = "0.2"
clap = { version = "3.0.0", features = ["cargo", "wrap_help", "unicode"] }
clipboard= "0.5.0"
